//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class paamelding {
    
    private paameldingOvelse[] ovelseField;
    
    private string stevnenavnField;
    
    private string stevnenummerField;
    
    private string arrangorField;
    
    private string stevnestartField;
    
    private string stevnesluttField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ovelse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public paameldingOvelse[] ovelse {
        get {
            return this.ovelseField;
        }
        set {
            this.ovelseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stevnenavn {
        get {
            return this.stevnenavnField;
        }
        set {
            this.stevnenavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stevnenummer {
        get {
            return this.stevnenummerField;
        }
        set {
            this.stevnenummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string arrangor {
        get {
            return this.arrangorField;
        }
        set {
            this.arrangorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stevnestart {
        get {
            return this.stevnestartField;
        }
        set {
            this.stevnestartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stevneslutt {
        get {
            return this.stevnesluttField;
        }
        set {
            this.stevnesluttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class paameldingOvelse {
    
    private paameldingOvelseLag[] lagField;
    
    private paameldingOvelsePaameldingskytter[] paameldingskytterField;
    
    private string idField;
    
    private string holdField;
    
    private string stangField;
    
    private string felthurtigField;
    
    private string minneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("lag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public paameldingOvelseLag[] lag {
        get {
            return this.lagField;
        }
        set {
            this.lagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paamelding-skytter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public paameldingOvelsePaameldingskytter[] paameldingskytter {
        get {
            return this.paameldingskytterField;
        }
        set {
            this.paameldingskytterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hold {
        get {
            return this.holdField;
        }
        set {
            this.holdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stang {
        get {
            return this.stangField;
        }
        set {
            this.stangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string felthurtig {
        get {
            return this.felthurtigField;
        }
        set {
            this.felthurtigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minne {
        get {
            return this.minneField;
        }
        set {
            this.minneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class paameldingOvelseLag {
    
    private string navnField;
    
    private string lagnrField;
    
    private string datoField;
    
    private string klskytetidField;
    
    private string kloppropField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string navn {
        get {
            return this.navnField;
        }
        set {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lagnr {
        get {
            return this.lagnrField;
        }
        set {
            this.lagnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dato {
        get {
            return this.datoField;
        }
        set {
            this.datoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kl-skytetid")]
    public string klskytetid {
        get {
            return this.klskytetidField;
        }
        set {
            this.klskytetidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kl-opprop")]
    public string klopprop {
        get {
            return this.kloppropField;
        }
        set {
            this.kloppropField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class paameldingOvelsePaameldingskytter {
    
    private string lagField;
    
    private string skiveField;
    
    private string medlemsidField;
    
    private string fornavnField;
    
    private string etternavnField;
    
    private string sklagnrField;
    
    private string epostField;
    
    private string fdatoField;
    
    private string endeskiveField;
    
    private string lS_ovelseField;
    
    private string klasseField;
    
    private string klassefeltField;
    
    private string klasseskogslopField;
    
    private string katmfField;
    
    private string katmbField;
    
    private string katkField;
    
    private string katlField;
    
    private string kataField;
    
    private string katnField;
    
    private string katftField;
    
    private string kat22Field;
    
    private string katluftField;
    
    private string gruppeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lag {
        get {
            return this.lagField;
        }
        set {
            this.lagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string skive {
        get {
            return this.skiveField;
        }
        set {
            this.skiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string medlemsid {
        get {
            return this.medlemsidField;
        }
        set {
            this.medlemsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fornavn {
        get {
            return this.fornavnField;
        }
        set {
            this.fornavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string etternavn {
        get {
            return this.etternavnField;
        }
        set {
            this.etternavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sklag-nr")]
    public string sklagnr {
        get {
            return this.sklagnrField;
        }
        set {
            this.sklagnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string epost {
        get {
            return this.epostField;
        }
        set {
            this.epostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fdato {
        get {
            return this.fdatoField;
        }
        set {
            this.fdatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string endeskive {
        get {
            return this.endeskiveField;
        }
        set {
            this.endeskiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LS_ovelse {
        get {
            return this.lS_ovelseField;
        }
        set {
            this.lS_ovelseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string klasse {
        get {
            return this.klasseField;
        }
        set {
            this.klasseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("klasse-felt")]
    public string klassefelt {
        get {
            return this.klassefeltField;
        }
        set {
            this.klassefeltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("klasse-skogslop")]
    public string klasseskogslop {
        get {
            return this.klasseskogslopField;
        }
        set {
            this.klasseskogslopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-mf")]
    public string katmf {
        get {
            return this.katmfField;
        }
        set {
            this.katmfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-mb")]
    public string katmb {
        get {
            return this.katmbField;
        }
        set {
            this.katmbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-k")]
    public string katk {
        get {
            return this.katkField;
        }
        set {
            this.katkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-l")]
    public string katl {
        get {
            return this.katlField;
        }
        set {
            this.katlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-a")]
    public string kata {
        get {
            return this.kataField;
        }
        set {
            this.kataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-n")]
    public string katn {
        get {
            return this.katnField;
        }
        set {
            this.katnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-ft")]
    public string katft {
        get {
            return this.katftField;
        }
        set {
            this.katftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-22")]
    public string kat22 {
        get {
            return this.kat22Field;
        }
        set {
            this.kat22Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("kat-luft")]
    public string katluft {
        get {
            return this.katluftField;
        }
        set {
            this.katluftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gruppe {
        get {
            return this.gruppeField;
        }
        set {
            this.gruppeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private paamelding[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paamelding")]
    public paamelding[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
